# Generated by Django 3.2.7 on 2024-03-31 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999)),
                ('slug', models.CharField(blank=True, max_length=9999, unique=True)),
                ('bio', models.TextField()),
                ('image', models.FileField(blank=True, default='author/profile.jpg', upload_to='authors/')),
                ('nationality', models.CharField(blank=True, max_length=99999, null=True)),
                ('is_bestseller', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=9999)),
                ('description', models.TextField()),
                ('product_image', models.FileField(blank=True, default='product/Product.jpg', upload_to='product/')),
                ('SKU', models.CharField(blank=True, max_length=9999, null=True)),
                ('stock_status', models.CharField(blank=True, choices=[('In stock', 'In stock'), ('Out of Stock', 'Out of Stock')], default='In Stock', max_length=9999, null=True)),
                ('stock_quantity', models.IntegerField(default=1)),
                ('sell_quantity', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('published_date', models.DateField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=9999, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('isbn_number', models.CharField(blank=True, max_length=9999, null=True)),
                ('language', models.CharField(choices=[('Nepali', 'Nepali'), ('English', 'English')], default='English', max_length=9999)),
                ('top_selling', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=True)),
                ('new_arrival', models.BooleanField(default=True)),
                ('is_used', models.BooleanField(default=False)),
                ('authors', models.ManyToManyField(related_name='products', to='product.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9999)),
                ('slug', models.CharField(max_length=9999, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('coupon_types', models.CharField(choices=[('Percentage Discount', 'Percentage Discount'), ('Flat Discount', 'Flat Discount'), ('Bulk Discount', 'Bulk Discount'), ('Free Shipping', 'Free Shipping')], default='Percentage Discount', max_length=400)),
                ('coupon_details', models.JSONField(blank=True, default=product.models.default_coupon_details, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlist_product', to='product.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=75, unique=True)),
                ('product', models.ManyToManyField(to='product.Book')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9999)),
                ('sub_slug', models.CharField(blank=True, max_length=9999, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_count', models.IntegerField()),
                ('review_text', models.CharField(max_length=400)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_product', to='product.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewing_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductQueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=999)),
                ('answer', models.CharField(max_length=999)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_product', to='product.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
    ]
