# Generated by Django 5.0.3 on 2024-03-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.CharField(blank=True, max_length=9999, null=True, unique=True),
        ),
    ]
