# Generated by Django 5.0.3 on 2024-04-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="expire_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="review_text",
            field=models.CharField(max_length=9999),
        ),
    ]
