# Generated by Django 5.0.3 on 2024-04-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_coupon_expire_at_alter_review_review_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="value",
            field=models.FloatField(default=0.0),
        ),
    ]
