# Generated by Django 5.0.3 on 2024-04-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_coupon_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.CharField(blank=True, max_length=9999, null=True, unique=True),
        ),
    ]
