# Generated by Django 5.0.3 on 2024-04-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_book_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="profile",
            field=models.FileField(
                blank=True, default="authors/profile.jpg", upload_to="category/"
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="image",
            field=models.FileField(
                blank=True, default="authors/profile.jpg", upload_to="authors/"
            ),
        ),
    ]
