# Generated by Django 5.0.3 on 2024-04-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_category_profile_alter_author_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="remaining_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
