# Generated by Django 5.0.3 on 2024-04-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_book_remaining_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="weight",
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
    ]
