# Generated by Django 5.0.3 on 2024-04-22 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_book_weight"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="profile",
            new_name="icon",
        ),
    ]
