# Generated by Django 5.0.3 on 2024-04-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_rename_profile_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="post_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
