# Generated by Django 5.0.3 on 2024-04-25 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_review_post_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="remaining_quantity",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
