# Generated by Django 5.0.3 on 2024-04-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_alter_book_remaining_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="language",
            field=models.CharField(
                choices=[
                    ("Nepali", "Nepali"),
                    ("English", "English"),
                    ("Hindi", "Hindi"),
                ],
                default="English",
                max_length=9999,
            ),
        ),
    ]
