# Generated by Django 5.0.3 on 2024-05-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_alter_book_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_popular",
            field=models.BooleanField(default=False),
        ),
    ]
