# Generated by Django 5.2.8 on 2025-11-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_rename_author_company_rename_book_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='authors',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('In stock', 'In stock'), ('Out of Stock', 'Out of Stock')], default='In stock', max_length=9999, null=True),
        ),
    ]
