# Generated by Django 5.2.8 on 2025-12-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rename_authors_product_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='isbn_number',
            new_name='product_code',
        ),
    ]
