# Generated by Django 5.2.8 on 2025-12-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_rename_isbn_number_product_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='page_count',
        ),
    ]
