# Generated by Django 3.2.7 on 2024-03-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=9999)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('description', models.TimeField()),
                ('image', models.ImageField(upload_to='careers_images/')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Carousal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=9999, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=9999, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('link_text', models.CharField(blank=True, max_length=999999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=99999)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9999)),
                ('url', models.CharField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('opt_out', models.BooleanField(default=False)),
            ],
        ),
    ]
