# Generated by Django 5.0.3 on 2024-04-08 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_faqstopic"),
    ]

    operations = [
        migrations.AddField(
            model_name="faqs",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.faqstopic",
            ),
        ),
    ]
