# Generated by Django 5.0.3 on 2024-04-08 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_faqs_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carousal",
            name="subtitle",
        ),
    ]
