# Generated by Django 5.0.3 on 2024-04-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_remove_carousal_subtitle"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacyPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=99999, null=True)),
                ("html_content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TermsAndCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=99999, null=True)),
                ("html_content", models.TextField()),
            ],
        ),
    ]
