# Generated by Django 5.0.3 on 2024-04-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_privacypolicy_termsandcondition"),
    ]

    operations = [
        migrations.AddField(
            model_name="careers",
            name="expire_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="careers",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
