# Generated by Django 5.2.8 on 2025-11-27 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_careers_expire_at_alter_careers_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careers',
            options={'verbose_name': 'Career', 'verbose_name_plural': 'Careers'},
        ),
        migrations.AlterModelOptions(
            name='carousal',
            options={'verbose_name': 'Carousel', 'verbose_name_plural': 'Carousels'},
        ),
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='faqstopic',
            options={'verbose_name': 'FAQ Topic', 'verbose_name_plural': 'FAQ Topics'},
        ),
        migrations.AlterModelOptions(
            name='menus',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Newsletter Subscription', 'verbose_name_plural': 'Newsletter Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'Privacy Policy', 'verbose_name_plural': 'Privacy Policies'},
        ),
        migrations.AlterModelOptions(
            name='termsandcondition',
            options={'verbose_name': 'Terms and Condition', 'verbose_name_plural': 'Terms and Conditions'},
        ),
        migrations.AlterField(
            model_name='careers',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='careers',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='careers',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='careers',
            name='image',
            field=models.ImageField(upload_to='careers_images/', verbose_name='Career Image'),
        ),
        migrations.AlterField(
            model_name='careers',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='careers',
            name='title',
            field=models.CharField(max_length=9999, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='carousal',
            name='image',
            field=models.ImageField(upload_to='carousel_images/', verbose_name='Carousel Image'),
        ),
        migrations.AlterField(
            model_name='carousal',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='carousal',
            name='link_text',
            field=models.CharField(blank=True, max_length=999999, null=True, verbose_name='Link Text'),
        ),
        migrations.AlterField(
            model_name='carousal',
            name='title',
            field=models.CharField(blank=True, max_length=9999, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='question',
            field=models.CharField(max_length=99999, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.faqstopic', verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='faqstopic',
            name='title',
            field=models.CharField(max_length=99999, verbose_name='Topic Title'),
        ),
        migrations.AlterField(
            model_name='menus',
            name='name',
            field=models.CharField(max_length=9999, verbose_name='Menu Name'),
        ),
        migrations.AlterField(
            model_name='menus',
            name='url',
            field=models.CharField(max_length=9999, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Subscriber Email'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='opt_out',
            field=models.BooleanField(default=False, verbose_name='Opted Out'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Subscribed At'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='html_content',
            field=models.TextField(verbose_name='Privacy Policy Content'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='name',
            field=models.CharField(blank=True, max_length=99999, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='termsandcondition',
            name='html_content',
            field=models.TextField(verbose_name='Terms and Conditions Content'),
        ),
        migrations.AlterField(
            model_name='termsandcondition',
            name='name',
            field=models.CharField(blank=True, max_length=99999, null=True, verbose_name='Title'),
        ),
    ]
