# Generated by Django 5.2.8 on 2025-11-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletteremail',
            options={'verbose_name': 'Newsletter Email', 'verbose_name_plural': 'Newsletter Emails'},
        ),
        migrations.AlterField(
            model_name='newsletteremail',
            name='content',
            field=models.TextField(verbose_name='Email Content'),
        ),
        migrations.AlterField(
            model_name='newsletteremail',
            name='topic',
            field=models.CharField(max_length=9999, verbose_name='Topic'),
        ),
    ]
