# Generated by Django 5.0.3 on 2024-04-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_comment_parent_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
