# Generated by Django 5.0.3 on 2024-04-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_blog_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
