# Generated by Django 5.0.3 on 2024-04-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_comment_comment_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_on",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
