# Generated by Django 5.0.3 on 2024-04-02 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0002_alter_category_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=99)),
                ("contact", models.CharField(max_length=99, unique=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("address", models.CharField(max_length=99, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buy_price", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="product.book"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply",
                        to="inventory.supplierdata",
                    ),
                ),
            ],
        ),
    ]
