# Generated by Django 5.0.3 on 2024-04-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile",
            field=models.FileField(
                blank=True, default="authors/profile.jpg", upload_to="customers/"
            ),
        ),
    ]
