# Generated by Django 3.2.7 on 2024-03-31 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=9999, null=True)),
                ('email', models.CharField(blank=True, max_length=99, null=True)),
                ('phone', models.CharField(blank=True, max_length=9999, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=9999, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=9999, null=True)),
                ('city', models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Lalitpur', 'Lalitpur'), ('Bhaktapur', 'Bhaktapur'), ('Bharatpur', 'Bharatpur'), ('Butwal', 'Butwal'), ('Bhairahawa', 'Bhairahawa'), ('Tansen', 'Tansen'), ('Biratnagar', 'Biratnagar')], max_length=9999)),
                ('country', models.CharField(choices=[('Nepal', 'Nepal')], default='Nepal', max_length=9999)),
                ('is_default', models.BooleanField(default=False, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=9999)),
                ('initial_price', models.FloatField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.book')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=9999, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Khalti', 'Khalti')], default='Cash On Delivery', max_length=9999)),
                ('amount', models.FloatField()),
                ('transaction_id', models.CharField(max_length=9999)),
                ('status', models.CharField(blank=True, max_length=9999, null=True)),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('initial_price', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('amount_to_pay', models.FloatField(blank=True, null=True)),
                ('coupon', models.CharField(blank=True, max_length=9999, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
                ('shipping_charge', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('All', 'All'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Failed', 'Failed')], default='Pending', max_length=9999)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=33)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('is_payment_verified', models.BooleanField(default=False)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.customeraddress')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order_qty', models.ManyToManyField(to='order.OrderQuantity')),
                ('payment_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.paymentdetail')),
            ],
        ),
    ]
