# Generated by Django 5.0.3 on 2024-04-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_paymentdetail_payment_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeraddress",
            name="city",
            field=models.CharField(
                choices=[
                    ("Pokhara", "Pokhara"),
                    ("Kathmandu", "Kathmandu"),
                    ("Biratnagar", "Biratnagar"),
                    ("Birgunj", "Birgunj"),
                    ("Hetauda", "Hetauda"),
                    ("Butwal", "Butwal"),
                    ("Bhairahawa", "Bhairahawa"),
                    ("Nepalgunj", "Nepalgunj"),
                    ("Bharatpur", "Bharatpur"),
                    ("Dhangadi", "Dhangadi"),
                    ("Dharan", "Dharan"),
                    ("Itahari", "Itahari"),
                    ("Damak", "Damak"),
                    ("Birtamode", "Birtamode"),
                    ("Janakpur", "Janakpur"),
                    ("Bardia", "Bardia"),
                    ("Dang", "Dang"),
                    ("Dhulikhel", "Dhulikhel"),
                    ("Bhaktapur", "Bhaktapur"),
                    ("Lalitpur", "Lalitpur"),
                    ("Surkhet", "Surkhet"),
                    ("Damauli", "Damauli"),
                    ("Banepa", "Banepa"),
                    ("Ghorai", "Ghorai"),
                    ("Bardaghat", "Bardaghat"),
                    ("Chandragadi", "Chandragadi"),
                    ("Parasi", "Parasi"),
                    ("Bhadrapur", "Bhadrapur"),
                    ("Sunawal", "Sunawal"),
                    ("Kakarvitta", "Kakarvitta"),
                    ("Kalaiya", "Kalaiya"),
                    ("Tilotama", "Tilotama"),
                    ("Lumbini", "Lumbini"),
                    ("Tulsipur", "Tulsipur"),
                    ("Narayanghat", "Narayanghat"),
                    ("Urlabari", "Urlabari"),
                    ("Nawalparasi", "Nawalparasi"),
                ],
                max_length=9999,
            ),
        ),
    ]
