# Generated by Django 5.2.8 on 2025-11-27 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_customeraddress_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'verbose_name': 'Customer Address', 'verbose_name_plural': 'Customer Addresses'},
        ),
        migrations.AlterModelOptions(
            name='orderquantity',
            options={'verbose_name': 'Order Quantity', 'verbose_name_plural': 'Order Quantities'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='paymentdetail',
            options={'verbose_name': 'Payment Detail', 'verbose_name_plural': 'Payment Details'},
        ),
    ]
